### PR TITLE
Make our own multicast group and join it.

### LINKED ISSUE #130: [OOB 5.6 r2] the default address (ff03::1) cannot work for multicast
I found the default address (ff03::1) is not for multicast. but the address (ff02::1) works well for multicast.
When making a socket with ff03::1, message could be sent for each button press, but no message could be received on the board sent the message, neither other boards connected locally.
Once I changed the address to ff02::1, the board sending message and other local boards can receive the message to turn on/off LED.
my test environment : 

- boarder router: K64F with Atmel RF233 (2.4G)

- LOWPAN_ROUTER: NUCLEO_F401RE with Atmel RF233 (2.4G) x 2   

- 6LoWPAN-ND, with no Thread 

- Since LED cannot be used on this board, there is a pin collision D13 between LED and SPI_SCK, I removed led on/off operation but kept LED turn on/off print.  

- tested on following 2 boarder router firmware versions. ff03::1 doesn't work on both conditions, but ff02::1 works well on both of them.

>  "backhaul-dynamic-bootstrap": false,   with a cable connected to IPv4 network
> "backhaul-dynamic-bootstrap": true,   with a cable connected to pure IPv6 network

I had made [a fix PR](https://github.com/ARMmbed/mbed-os-example-mesh-minimal/pull/131).

### PR DESCRIPTION
**Pull request by SeppoTakalo**
Do not rely on any default multicast groups to be enabled.
Don't spam nodes which have not joined our group.

Fixes #130

This needs to be manually tested for both Thread and 6LoWPAN.

### CODE REVIEW

File: mesh_led_control_example.cpp [hunk 1]
```diff
@@ -192,8 +191,15 @@ static void init_socket()
 {
     my_socket = new UDPSocket(network_if);
     my_socket->set_blocking(false);
-    my_socket->bind(UDP_PORT);    
+    my_socket->bind(UDP_PORT);
     my_socket->setsockopt(SOCKET_IPPROTO_IPV6, SOCKET_IPV6_MULTICAST_HOPS, &multicast_hops, sizeof(multicast_hops));
+
+    ns_ipv6_mreq_t mreq;
+    memcpy(mreq.ipv6mr_multiaddr, multi_cast_addr, 16);
+    mreq.ipv6mr_interface = 0;
```
Comment (karsev) [inline mesh_led_control_example.cpp]: Why zero? Can it change?

Comment (kjbracey-arm) [reply mesh_led_control_example.cpp]: Zero means "default". Best we can do as we don't have visibility of Nanostack interface IDs.

There is a PR going through to add a generic NSAPI for this - https://github.com/ARMmbed/mbed-os/pull/4820. That is intending to use interface address instead.

**Comment by karsev** [comment]
Verified!
